# 03 – Datenvalidierung

Dieses Notebook validiert den bereinigten Datensatz in zwei Runden:
1. Nach der Imputation (Rohdaten-Check)
2. Nach der Typkonvertierung (Schema-Check)

Validierungsregeln sind in `config.py` als Pandera-Schema definiert.

In [1]:
import sys
import polars as pl
from pathlib import Path

current_dir = Path('..') / '03_src'
sys.path.append(str(current_dir))
root_dir = Path('..')

from config import Schema
from data_validation import double_numbers, detect_outliers, check_data_quality
from data_cleaner import check_amount_nulls

## 3.1 Daten laden

In [2]:
data_combined_cleaned = pl.read_parquet(
    str(root_dir / '02_data' / 'processed' / 'combined_data_cleaned.parquet')
)
print(f'Zeilen: {len(data_combined_cleaned)} | Spalten: {len(data_combined_cleaned.columns)}')

Zeilen: 937456 | Spalten: 140

## 3.2 Duplikaten-Check

In [3]:
double_numbers(data_combined_cleaned)

Anzahl der Zeilen die Duplikate sind: 0

0

## 3.3 Ausreißer-Erkennung

In [4]:
detect_outliers(data_combined_cleaned)

--- Detaillierte Ausreißer-Analyse (IQR) ---
kwh_returned_total                            |   230402 ( 24.58%)
   -> Extremwerte (Top 10 absteigend): [223.36, 221.97, 215.98, 215.18, 214.59, 213.65, 212.76, 212.15, 209.0, 208.2]

coolingdegree_us_daily                        |   186242 ( 19.87%)
   -> Extremwerte (Top 10 absteigend): [10.6, 10.6, 10.6, 10.6, 10.6, 10.6, 10.6, 10.6, 10.6, 10.6]

precipitation_total_daily                     |   122357 ( 13.05%)
   -> Extremwerte (Top 10 absteigend): [79.6, 79.6, 79.6, 79.6, 79.6, 79.6, 79.6, 79.6, 79.6, 79.6]

building_floorareaheated_total                |    90221 (  9.62%)
   -> Extremwerte (Top 10 absteigend): [455.0, 455.0, 455.0, 455.0, 455.0, 455.0, 455.0, 455.0, 455.0, 455.0]

building_constructionyear                     |    84145 (  8.98%)
   -> Extremwerte (Top 10 absteigend): [2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020]

swissix_base                                  |    70402 (  7.51%)
   -> Extremwerte (Top 10 absteigend): [724.8658333333333, 724.8658333333333, 724.8658333333333, 724.8658333333333, 724.8658333333333, 724.8658333333333, 724.8658333333333, 724.8658333333333, 724.8658333333333, 724.8658333333333]

building_residents                            |    44919 (  4.79%)
   -> Extremwerte (Top 10 absteigend): [7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0]

kwh_received_total                            |    37200 (  3.97%)
   -> Extremwerte (Top 10 absteigend): [4689.98, 597.41, 589.52, 578.77, 575.09, 503.18, 502.33, 499.01, 496.48, 495.28]

kwh_received_heatpump                         |    35694 (  3.81%)
   -> Extremwerte (Top 10 absteigend): [401.96, 398.82, 391.2, 384.9, 384.55, 382.3, 377.09, 375.11, 371.6, 367.89]

building_floorareaheated_basement             |    32269 (  3.44%)
   -> Extremwerte (Top 10 absteigend): [160.0, 160.0, 160.0, 160.0, 160.0, 160.0, 160.0, 160.0, 160.0, 160.0]

heatdistribution_expansiontank_systemheight   |    17462 (  1.86%)
   -> Extremwerte (Top 10 absteigend): [12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0]

building_pvsystem_size                        |    10625 (  1.13%)
   -> Extremwerte (Top 10 absteigend): [18.5, 18.5, 18.5, 18.5, 18.5, 18.5, 18.5, 18.5, 18.5, 18.5]

building_floorareaheated_topfloor             |    10063 (  1.07%)
   -> Extremwerte (Top 10 absteigend): [120.0, 120.0, 120.0, 120.0, 120.0, 120.0, 120.0, 120.0, 120.0, 120.0]

visit_year                                    |     9426 (  1.01%)
   -> Extremwerte (Top 10 absteigend): [2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020]

building_floorareaheated_secondfloor          |     8783 (  0.94%)
   -> Extremwerte (Top 10 absteigend): [80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0]

building_housingunits                         |     6282 (  0.67%)
   -> Extremwerte (Top 10 absteigend): [3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0]

heatdistribution_expansiontank_pressure_target |     5581 (  0.60%)
   -> Extremwerte (Top 10 absteigend): [1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3]

heatpump_installation_refrigerant_content     |     5569 (  0.59%)
   -> Extremwerte (Top 10 absteigend): [145.0, 145.0, 145.0, 145.0, 145.0, 145.0, 145.0, 145.0, 145.0, 145.0]

heatpump_heatinglimitsetting_beforevisit      |     5332 (  0.57%)
   -> Extremwerte (Top 10 absteigend): [21, 21, 21, 21, 21, 21, 21, 21, 21, 21]

heatpump_installation_heatingcapacity         |     4009 (  0.43%)
   -> Extremwerte (Top 10 absteigend): [26.0, 26.0, 26.0, 26.0, 26.0, 26.0, 26.0, 26.0, 26.0, 26.0]

building_floorareaheated_groundfloor          |     3075 (  0.33%)
   -> Extremwerte (Top 10 absteigend): [300.0, 300.0, 300.0, 300.0, 300.0, 300.0, 300.0, 300.0, 300.0, 300.0]

heatpump_electricityconsumption_yearlyestimated |     2967 (  0.32%)
   -> Extremwerte (Top 10 absteigend): [17500.0, 17500.0, 17500.0, 17500.0, 17500.0, 17500.0, 17500.0, 17500.0, 17500.0, 17500.0]

dhw_storage_lastdescaling_year                |     2582 (  0.28%)
   -> Extremwerte (Top 10 absteigend): [2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007]

kwh_received_other                            |     2138 (  0.23%)
   -> Extremwerte (Top 10 absteigend): [171.97, 170.73, 169.58, 169.5, 168.29, 165.48, 164.39, 162.96, 160.16, 159.73]

report_id                                     |     2013 (  0.21%)
   -> Extremwerte (Top 10 absteigend): [40, 40, 40, 40, 40, 40, 40, 40, 40, 40]

heatpump_installation_year                    |     2009 (  0.21%)
   -> Extremwerte (Top 10 absteigend): [1983, 1983, 1983, 1983, 1983, 1983, 1983, 1983, 1983, 1983]

heatpump_heatingcurvesetting_outside20_beforevisit |     1893 (  0.20%)
   -> Extremwerte (Top 10 absteigend): [30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0]

heatpump_heatingcurvesetting_outside0_beforevisit |     1274 (  0.14%)
   -> Extremwerte (Top 10 absteigend): [60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0]

heatpump_groundsource_currenttemperature      |     1091 (  0.12%)
   -> Extremwerte (Top 10 absteigend): [20.3, 20.3, 20.3, 20.3, 20.3, 20.3, 20.3, 20.3, 20.3, 20.3]

humidity_avg_daily                            |      955 (  0.10%)
   -> Extremwerte (Top 10 absteigend): [42.6, 42.6, 42.6, 42.6, 42.6, 42.6, 42.6, 42.6, 42.6, 42.6]

building_floorareaheated_additionalareasplannedsize |      433 (  0.05%)
   -> Extremwerte (Top 10 absteigend): [300.0, 300.0, 300.0, 300.0, 300.0, 300.0, 300.0, 300.0, 300.0, 300.0]

heatpump_installation_normpoint_electricpower |      433 (  0.05%)
   -> Extremwerte (Top 10 absteigend): [7.07, 7.07, 7.07, 7.07, 7.07, 7.07, 7.07, 7.07, 7.07, 7.07]

heatpump_installation_normpoint_heatingpower  |      433 (  0.05%)
   -> Extremwerte (Top 10 absteigend): [23.7, 23.7, 23.7, 23.7, 23.7, 23.7, 23.7, 23.7, 23.7, 23.7]

heatpump_groundsource_brinecircuit_length     |      381 (  0.04%)
   -> Extremwerte (Top 10 absteigend): [360.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0, 360.0]

heatpump_groundsource_brinecircuit_numberofholes |      381 (  0.04%)
   -> Extremwerte (Top 10 absteigend): [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]

heatpump_heatingcurvesetting_outside20_aftervisit |      366 (  0.04%)
   -> Extremwerte (Top 10 absteigend): [26.0, 26.0, 26.0, 26.0, 26.0, 26.0, 26.0, 26.0, 26.0, 26.0]

heatpump_groundsource_brinecircuit_depth      |      272 (  0.03%)
   -> Extremwerte (Top 10 absteigend): [70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0]

building_floorareaheated_firstfloor           |      119 (  0.01%)
   -> Extremwerte (Top 10 absteigend): [170.0, 170.0, 170.0, 170.0, 170.0, 170.0, 170.0, 170.0, 170.0, 170.0]

heatpump_heatingcurvesetting_outsideminus8_beforevisit |       22 (  0.00%)
   -> Extremwerte (Top 10 absteigend): [65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0]

temperature_min_daily                         |       18 (  0.00%)
   -> Extremwerte (Top 10 absteigend): [-15.9, -15.9, -15.9, -15.9, -15.9, -17.7, -17.7, -17.7, -17.7, -17.7]

[{'spalte': 'kwh_returned_total',
  'anzahl': 230402,
  'prozent': 24.57736683108327,
  'extremwerte': [223.36,
   221.97,
   215.98,
   215.18,
   214.59,
   213.65,
   212.76,
   212.15,
   209.0,
   208.2]},
 {'spalte': 'coolingdegree_us_daily',
  'anzahl': 186242,
  'prozent': 19.866745745933674,
  'extremwerte': [10.6, 10.6, 10.6, 10.6, 10.6, 10.6, 10.6, 10.6, 10.6, 10.6]},
 {'spalte': 'precipitation_total_daily',
  'anzahl': 122357,
  'prozent': 13.052025908415969,
  'extremwerte': [79.6, 79.6, 79.6, 79.6, 79.6, 79.6, 79.6, 79.6, 79.6, 79.6]},
 {'spalte': 'building_floorareaheated_total',
  'anzahl': 90221,
  'prozent': 9.624025020907649,
  'extremwerte': [455.0,
   455.0,
   455.0,
   455.0,
   455.0,
   455.0,
   455.0,
   455.0,
   455.0,
   455.0]},
 {'spalte': 'building_constructionyear',
  'anzahl': 84145,
  'prozent': 8.975887935007083,
  'extremwerte': [2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020]},
 {'spalte': 'swissix_base',
  'anzahl': 70402,
  'prozent': 7.509899131265894,
  'extremwerte': [724.8658333333333,
   724.8658333333333,
   724.8658333333333,
   724.8658333333333,
   724.8658333333333,
   724.8658333333333,
   724.8658333333333,
   724.8658333333333,
   724.8658333333333,
   724.8658333333333]},
 {'spalte': 'building_residents',
  'anzahl': 44919,
  'prozent': 4.7915848850506055,
  'extremwerte': [7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0, 7.0]},
 {'spalte': 'kwh_received_total',
  'anzahl': 37200,
  'prozent': 3.9681862402075407,
  'extremwerte': [4689.98,
   597.41,
   589.52,
   578.77,
   575.09,
   503.18,
   502.33,
   499.01,
   496.48,
   495.28]},
 {'spalte': 'kwh_received_heatpump',
  'anzahl': 35694,
  'prozent': 3.807538700483009,
  'extremwerte': [401.96,
   398.82,
   391.2,
   384.9,
   384.55,
   382.3,
   377.09,
   375.11,
   371.6,
   367.89]},
 {'spalte': 'building_floorareaheated_basement',
  'anzahl': 32269,
  'prozent': 3.4421882200337937,
  'extremwerte': [160.0,
   160.0,
   160.0,
   160.0,
   160.0,
   160.0,
   160.0,
   160.0,
   160.0,
   160.0]},
 {'spalte': 'heatdistribution_expansiontank_systemheight',
  'anzahl': 17462,
  'prozent': 1.8627007560888191,
  'extremwerte': [12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0, 12.0]},
 {'spalte': 'building_pvsystem_size',
  'anzahl': 10625,
  'prozent': 1.1333865269409977,
  'extremwerte': [18.5, 18.5, 18.5, 18.5, 18.5, 18.5, 18.5, 18.5, 18.5, 18.5]},
 {'spalte': 'building_floorareaheated_topfloor',
  'anzahl': 10063,
  'prozent': 1.0734370466453893,
  'extremwerte': [120.0,
   120.0,
   120.0,
   120.0,
   120.0,
   120.0,
   120.0,
   120.0,
   120.0,
   120.0]},
 {'spalte': 'visit_year',
  'anzahl': 9426,
  'prozent': 1.0054871908654914,
  'extremwerte': [2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020, 2020]},
 {'spalte': 'building_floorareaheated_secondfloor',
  'anzahl': 8783,
  'prozent': 0.9368973050468502,
  'extremwerte': [80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0, 80.0]},
 {'spalte': 'building_housingunits',
  'anzahl': 6282,
  'prozent': 0.6701114505640797,
  'extremwerte': [3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0, 3.0]},
 {'spalte': 'heatdistribution_expansiontank_pressure_target',
  'anzahl': 5581,
  'prozent': 0.595334607704255,
  'extremwerte': [1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3, 1.3]},
 {'spalte': 'heatpump_installation_refrigerant_content',
  'anzahl': 5569,
  'prozent': 0.5940545476267686,
  'extremwerte': [145.0,
   145.0,
   145.0,
   145.0,
   145.0,
   145.0,
   145.0,
   145.0,
   145.0,
   145.0]},
 {'spalte': 'heatpump_heatinglimitsetting_beforevisit',
  'anzahl': 5332,
  'prozent': 0.5687733610964142,
  'extremwerte': [21, 21, 21, 21, 21, 21, 21, 21, 21, 21]},
 {'spalte': 'heatpump_installation_heatingcapacity',
  'anzahl': 4009,
  'prozent': 0.42764673755354915,
  'extremwerte': [26.0, 26.0, 26.0, 26.0, 26.0, 26.0, 26.0, 26.0, 26.0, 26.0]},
 {'spalte': 'building_floorareaheated_groundfloor',
  'anzahl': 3075,
  'prozent': 0.3280153948558652,
  'extremwerte': [300.0,
   300.0,
   300.0,
   300.0,
   300.0,
   300.0,
   300.0,
   300.0,
   300.0,
   300.0]},
 {'spalte': 'heatpump_electricityconsumption_yearlyestimated',
  'anzahl': 2967,
  'prozent': 0.3164948541584885,
  'extremwerte': [17500.0,
   17500.0,
   17500.0,
   17500.0,
   17500.0,
   17500.0,
   17500.0,
   17500.0,
   17500.0,
   17500.0]},
 {'spalte': 'dhw_storage_lastdescaling_year',
  'anzahl': 2582,
  'prozent': 0.27542626000580295,
  'extremwerte': [2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007, 2007]},
 {'spalte': 'kwh_received_other',
  'anzahl': 2138,
  'prozent': 0.22806403713880968,
  'extremwerte': [171.97,
   170.73,
   169.58,
   169.5,
   168.29,
   165.48,
   164.39,
   162.96,
   160.16,
   159.73]},
 {'spalte': 'report_id',
  'anzahl': 2013,
  'prozent': 0.21473007799832738,
  'extremwerte': [40, 40, 40, 40, 40, 40, 40, 40, 40, 40]},
 {'spalte': 'heatpump_installation_year',
  'anzahl': 2009,
  'prozent': 0.21430339130583195,
  'extremwerte': [1983, 1983, 1983, 1983, 1983, 1983, 1983, 1983, 1983, 1983]},
 {'spalte': 'heatpump_heatingcurvesetting_outside20_beforevisit',
  'anzahl': 1893,
  'prozent': 0.20192947722346435,
  'extremwerte': [30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0, 30.0]},
 {'spalte': 'heatpump_heatingcurvesetting_outside0_beforevisit',
  'anzahl': 1274,
  'prozent': 0.13589971155979588,
  'extremwerte': [60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0, 60.0]},
 {'spalte': 'heatpump_groundsource_currenttemperature',
  'anzahl': 1091,
  'prozent': 0.11637879537812976,
  'extremwerte': [20.3, 20.3, 20.3, 20.3, 20.3, 20.3, 20.3, 20.3, 20.3, 20.3]},
 {'spalte': 'humidity_avg_daily',
  'anzahl': 955,
  'prozent': 0.10187144783328497,
  'extremwerte': [42.6, 42.6, 42.6, 42.6, 42.6, 42.6, 42.6, 42.6, 42.6, 42.6]},
 {'spalte': 'building_floorareaheated_additionalareasplannedsize',
  'anzahl': 433,
  'prozent': 0.04618883446263078,
  'extremwerte': [300.0,
   300.0,
   300.0,
   300.0,
   300.0,
   300.0,
   300.0,
   300.0,
   300.0,
   300.0]},
 {'spalte': 'heatpump_installation_normpoint_electricpower',
  'anzahl': 433,
  'prozent': 0.04618883446263078,
  'extremwerte': [7.07, 7.07, 7.07, 7.07, 7.07, 7.07, 7.07, 7.07, 7.07, 7.07]},
 {'spalte': 'heatpump_installation_normpoint_heatingpower',
  'anzahl': 433,
  'prozent': 0.04618883446263078,
  'extremwerte': [23.7, 23.7, 23.7, 23.7, 23.7, 23.7, 23.7, 23.7, 23.7, 23.7]},
 {'spalte': 'heatpump_groundsource_brinecircuit_length',
  'anzahl': 381,
  'prozent': 0.04064190746019013,
  'extremwerte': [360.0,
   360.0,
   360.0,
   360.0,
   360.0,
   360.0,
   360.0,
   360.0,
   360.0,
   360.0]},
 {'spalte': 'heatpump_groundsource_brinecircuit_numberofholes',
  'anzahl': 381,
  'prozent': 0.04064190746019013,
  'extremwerte': [2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0, 2.0]},
 {'spalte': 'heatpump_heatingcurvesetting_outside20_aftervisit',
  'anzahl': 366,
  'prozent': 0.03904183236333225,
  'extremwerte': [26.0, 26.0, 26.0, 26.0, 26.0, 26.0, 26.0, 26.0, 26.0, 26.0]},
 {'spalte': 'heatpump_groundsource_brinecircuit_depth',
  'anzahl': 272,
  'prozent': 0.029014695089689544,
  'extremwerte': [70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0, 70.0]},
 {'spalte': 'building_floorareaheated_firstfloor',
  'anzahl': 119,
  'prozent': 0.012693929101739176,
  'extremwerte': [170.0,
   170.0,
   170.0,
   170.0,
   170.0,
   170.0,
   170.0,
   170.0,
   170.0,
   170.0]},
 {'spalte': 'heatpump_heatingcurvesetting_outsideminus8_beforevisit',
  'anzahl': 22,
  'prozent': 0.0023467768087248896,
  'extremwerte': [65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0]},
 {'spalte': 'temperature_min_daily',
  'anzahl': 18,
  'prozent': 0.0019200901162294548,
  'extremwerte': [-15.9,
   -15.9,
   -15.9,
   -15.9,
   -15.9,
   -17.7,
   -17.7,
   -17.7,
   -17.7,
   -17.7]}]

## 3.4 Schema-Validierung (Pandera)

In [5]:
check_data_quality(data_combined_cleaned, Schema)

✅ Validierung erfolgreich: Der Dataframe entspricht dem Schema!

shape: (937_456, 140)
┌───────────┬───────────┬───────────┬──────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ timestamp ┆ timestamp ┆ date      ┆ year_str ┆ … ┆ heatdistr ┆ visit_dat ┆ year_str_ ┆ swissix_b │
│ ---       ┆ _local    ┆ ---       ┆ ---      ┆   ┆ ibution_r ┆ e_date    ┆ right     ┆ ase       │
│ datetime[ ┆ ---       ┆ date      ┆ str      ┆   ┆ ecommenda ┆ ---       ┆ ---       ┆ ---       │
│ μs, UTC]  ┆ datetime[ ┆           ┆          ┆   ┆ tio…      ┆ date      ┆ str       ┆ f64       │
│           ┆ μs, Europ ┆           ┆          ┆   ┆ ---       ┆           ┆           ┆           │
│           ┆ e/Zurich] ┆           ┆          ┆   ┆ bool      ┆           ┆           ┆           │
╞═══════════╪═══════════╪═══════════╪══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2019-03-0 ┆ 2019-03-0 ┆ 2019-03-0 ┆ 2019     ┆ … ┆ false     ┆ null      ┆ null      ┆ 22.79     │
│ 2         ┆ 3         ┆ 3         ┆          ┆   ┆           ┆           ┆           ┆           │
│ 23:59:59  ┆ 00:59:59  ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ UTC       ┆ CET       ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2019-03-0 ┆ 2019-03-0 ┆ 2019-03-0 ┆ 2019     ┆ … ┆ false     ┆ null      ┆ null      ┆ 37.938333 │
│ 3         ┆ 4         ┆ 4         ┆          ┆   ┆           ┆           ┆           ┆           │
│ 23:59:59  ┆ 00:59:59  ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ UTC       ┆ CET       ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2019-03-0 ┆ 2019-03-0 ┆ 2019-03-0 ┆ 2019     ┆ … ┆ false     ┆ null      ┆ null      ┆ 37.9225   │
│ 4         ┆ 5         ┆ 5         ┆          ┆   ┆           ┆           ┆           ┆           │
│ 23:59:59  ┆ 00:59:59  ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ UTC       ┆ CET       ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2019-03-0 ┆ 2019-03-0 ┆ 2019-03-0 ┆ 2019     ┆ … ┆ false     ┆ null      ┆ null      ┆ 40.97875  │
│ 5         ┆ 6         ┆ 6         ┆          ┆   ┆           ┆           ┆           ┆           │
│ 23:59:59  ┆ 00:59:59  ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ UTC       ┆ CET       ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2019-03-0 ┆ 2019-03-0 ┆ 2019-03-0 ┆ 2019     ┆ … ┆ false     ┆ null      ┆ null      ┆ 34.819167 │
│ 6         ┆ 7         ┆ 7         ┆          ┆   ┆           ┆           ┆           ┆           │
│ 23:59:59  ┆ 00:59:59  ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ UTC       ┆ CET       ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ …         ┆ …         ┆ …         ┆ …        ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 2024-03-1 ┆ 2024-03-1 ┆ 2024-03-1 ┆ 2024     ┆ … ┆ false     ┆ null      ┆ null      ┆ 60.337917 │
│ 6         ┆ 7         ┆ 7         ┆          ┆   ┆           ┆           ┆           ┆           │
│ 23:59:59  ┆ 00:59:59  ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ UTC       ┆ CET       ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2024-03-1 ┆ 2024-03-1 ┆ 2024-03-1 ┆ 2024     ┆ … ┆ false     ┆ null      ┆ null      ┆ 81.739583 │
│ 7         ┆ 8         ┆ 8         ┆          ┆   ┆           ┆           ┆           ┆           │
│ 23:59:59  ┆ 00:59:59  ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ UTC       ┆ CET       ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2024-03-1 ┆ 2024-03-1 ┆ 2024-03-1 ┆ 2024     ┆ … ┆ false     ┆ null      ┆ null      ┆ 84.41875  │
│ 8         ┆ 9         ┆ 9         ┆          ┆   ┆           ┆           ┆           ┆           │
│ 23:59:59  ┆ 00:59:59  ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ UTC       ┆ CET       ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2024-03-1 ┆ 2024-03-2 ┆ 2024-03-2 ┆ 2024     ┆ … ┆ false     ┆ null      ┆ null      ┆ 90.577083 │
│ 9         ┆ 0         ┆ 0         ┆          ┆   ┆           ┆           ┆           ┆           │
│ 23:59:59  ┆ 00:59:59  ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ UTC       ┆ CET       ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ 2024-03-2 ┆ 2024-03-2 ┆ 2024-03-2 ┆ 2024     ┆ … ┆ false     ┆ null      ┆ null      ┆ 78.08     │
│ 0         ┆ 1         ┆ 1         ┆          ┆   ┆           ┆           ┆           ┆           │
│ 23:59:59  ┆ 00:59:59  ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
│ UTC       ┆ CET       ┆           ┆          ┆   ┆           ┆           ┆           ┆           │
└───────────┴───────────┴───────────┴──────────┴───┴───────────┴───────────┴───────────┴───────────┘

## 3.5 Nullwerte im finalen Datensatz

In [6]:
check_amount_nulls(data_combined_cleaned)

---------------------------------------------
TOP 20 SPALTEN MIT MEISTEN NULLS
Datensatz: 937,456 Zeilen | 140 Spalten
Spalten mit Nulls: 20
---------------------------------------------
shape: (20, 3)
┌─────────────────────────────────┬────────────┬───────┐
│ spalte                          ┆ null_count ┆ pct   │
│ ---                             ┆ ---        ┆ ---   │
│ str                             ┆ u32        ┆ f64   │
╞═════════════════════════════════╪════════════╪═══════╡
│ visit_date_date                 ┆ 937456     ┆ 100.0 │
│ year_str_right                  ┆ 937456     ┆ 100.0 │
│ heatpump_groundsource_brinecir… ┆ 935674     ┆ 99.81 │
│ heatdistribution_circulation_p… ┆ 934015     ┆ 99.63 │
│ heatdistribution_circulation_p… ┆ 933978     ┆ 99.63 │
│ heatpump_groundsource_brinecir… ┆ 933780     ┆ 99.61 │
│ heatpump_groundsource_brinecir… ┆ 933399     ┆ 99.57 │
│ heatpump_groundsource_currentp… ┆ 933165     ┆ 99.54 │
│ heatpump_groundsource_currentt… ┆ 928403     ┆ 99.03 │
│ building_floorareaheated_addit… ┆ 928123     ┆ 99.0  │
│ dhw_temperaturesetting_aftervi… ┆ 926835     ┆ 98.87 │
│ heatpump_groundsource_brinecir… ┆ 926320     ┆ 98.81 │
│ heatpump_heatinglimitsetting_a… ┆ 910833     ┆ 97.16 │
│ kwh_received_other              ┆ 908381     ┆ 96.9  │
│ heatpump_heatingcurvesetting_o… ┆ 906858     ┆ 96.74 │
│ heatpump_heatingcurvesetting_o… ┆ 906130     ┆ 96.66 │
│ heatpump_heatinglimitsetting_b… ┆ 905064     ┆ 96.54 │
│ heatpump_installation_controll… ┆ 902899     ┆ 96.31 │
│ heatpump_heatingcurvesetting_o… ┆ 902406     ┆ 96.26 │
│ heatpump_installation_normpoin… ┆ 902279     ┆ 96.25 │
└─────────────────────────────────┴────────────┴───────┘

shape: (20, 3)
┌─────────────────────────────────┬────────────┬───────┐
│ spalte                          ┆ null_count ┆ pct   │
│ ---                             ┆ ---        ┆ ---   │
│ str                             ┆ u32        ┆ f64   │
╞═════════════════════════════════╪════════════╪═══════╡
│ visit_date_date                 ┆ 937456     ┆ 100.0 │
│ year_str_right                  ┆ 937456     ┆ 100.0 │
│ heatpump_groundsource_brinecir… ┆ 935674     ┆ 99.81 │
│ heatdistribution_circulation_p… ┆ 934015     ┆ 99.63 │
│ heatdistribution_circulation_p… ┆ 933978     ┆ 99.63 │
│ …                               ┆ …          ┆ …     │
│ heatpump_heatingcurvesetting_o… ┆ 906130     ┆ 96.66 │
│ heatpump_heatinglimitsetting_b… ┆ 905064     ┆ 96.54 │
│ heatpump_installation_controll… ┆ 902899     ┆ 96.31 │
│ heatpump_heatingcurvesetting_o… ┆ 902406     ┆ 96.26 │
│ heatpump_installation_normpoin… ┆ 902279     ┆ 96.25 │
└─────────────────────────────────┴────────────┴───────┘